name: Build Nuxt
on: [push]
jobs:
  build_nuxt:
    runs-on: ubuntu-latest
    name: Build Nuxt
    steps:
    - uses: actions/checkout@v3
    - id: Build-Nuxt
      uses: khanshifaul/NuxtPagesAction
      with:
        username: 'khanshifaul'
        reponame: 'SHOTODOL_HEALTH'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged